apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
  namespace: openfuyao-system
  labels:
    app: marketplace-service
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  type: ClusterIP
  ports:
    - name: transport
      port: 80
      protocol: TCP
      {{- if .Values.enableOAuth }}
      targetPort: proxy
      {{- else }}
      targetPort: {{ .Values.config.httpServerConfig.port }}
      {{- end }}
    - port: 9038
      targetPort: 9038
      protocol: TCP
      name: rpc
  publishNotReadyAddresses: true
  selector:
    app: marketplace-service
  sessionAffinity: None

